### ISSUE TITLE
Get All Scripts GET https://api.bigcommerce.com /stores/{store_hash}/v3/content/scripts response undefined.

### ISSUE THREAD

**Issue by ersanjay5991** [bigcommerce/sample-app-nodejs#156]
I am using this repo I am trying to get the list of scripts before reading the script I have created the script successfully using this ref. https://developer.bigcommerce.com/api-reference/99ba5fd00ad56-create-a-script

I can see the js loaded on storefronts but when I query big commerce it gave me a response undefined.
```
 // get list of scripts 
      const { data_read_sc } = await bigcommerce.get('/content/scripts');
      console.log(" reading the script  ",data_read_sc)

```

Output 

```
reading the script   undefined

```

**Comment by bc-chaz** [comment]
Hi @ersanjay5991 the GitHub Issues section of this repo is for bugs and issues related to the Sample Application. The questions you have are related to our general APIs. For support, please check out our [support page](https://developer.bigcommerce.com/docs/ZG9jOjM4MzMyNTU-support), which includes links to our Developer Community, Blog, and [Partner Support Team](https://partners.bigcommerce.com/English/). As this isn't an issue with the Sample Application, I will close this ticket.

In regards to your question, the issue appears to be that `data_read_sc` is not a property of the return response - please scroll down in the documentation and review the response - https://developer.bigcommerce.com/api-reference/5cb1b616e2e42-get-all-scripts#response-body. i.e. `data` is returned and that is an array of scripts.

**Comment by ersanjay5991** [comment]
@bc-chaz  thanks lot.
