### ISSUE TITLE
Can't connect to mysql database

### ISSUE THREAD

**Issue by thanhbinh8703** [bigcommerce/sample-app-nodejs#54]
Hi, 

I tried create sample app and enter mysql connect and get error TypeError: Cannot read property 'host' of undefined

![image](https://user-images.githubusercontent.com/88182921/127952319-350f3401-42fe-4f6c-9c68-def54c81eb73.png)

**Comment by urbanovich** [comment]
Hi @thanhbinh8703!

Check you local environments like this:
`const MYSQL_CONFIG = {
    host: process.env.MYSQL_HOST,
    database: process.env.MYSQL_DATABASE,
    user: process.env.MYSQL_USERNAME,
    password: process.env.MYSQL_PASSWORD,
    ...(process.env.MYSQL_PORT && { port: process.env.MYSQL_PORT }),
};`

**Comment by bc-chaz** [comment]
haven't seen any recent activity - closing for now
