### ISSUE TITLE
Issues deploying to Heroku

### ISSUE THREAD

**Issue by Yuri-Karpenko** [bigcommerce/sample-app-nodejs#80]
When deploying to Heroku, getting this error (below). Any thoughts on how to fix it?

-----> Installing dependencies
       Installing node modules
       npm ERR! code EINTEGRITY
       npm ERR! sha512-oU39CH8fMpZw/QHAlfYgaceTM7kPHBbVPiJvKzSKtlkzYixAaB97UwReN1IKF+kdLL/tIOZDGKRZoJS5ZyAkNA== integrity checksum failed when using sha512: wanted sha512-oU39CH8fMpZw/QHAlfYgaceTM7kPHBbVPiJvKzSKtlkzYixAaB97UwReN1IKF+kdLL/tIOZDGKRZoJS5ZyAkNA== but got sha512-BtCkKT5/o5gGLHE78+zP84J0XhTYLNdhXEdFwwsDPKLeQ0P9dyjk3lc801oY3lj32see/nZdpfTkI8u4WyGPBw==. (11161 bytes)
       
       npm ERR! A complete log of this run can be found in:
       npm ERR!     /tmp/npmcache.BpYmC/_logs/2022-01-09T08_29_06_464Z-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       If you're stuck, please submit a ticket so we can help:
       https://help.heroku.com/
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.
 !     Push failed

**Comment by bc-chaz** [comment]
@Yuri-Karpenko please see https://github.com/bigcommerce/sample-app-nodejs/issues/88
